### ISSUE TITLE
small improvements

### ISSUE THREAD

**Issue by Sharrnah** [rokujyushi/WT2TALQu#1]
Hello. First thank you a lot for the first 3rd party plugin. :) Really appreciate it.

I checked the plugin and found some things i am not 100% sure about.

- In the stt and tts methods, `self.target_sample_rate` and `self.play_audio_on_device()` are not defined.
   - that will probably prevent it from being able to play the audio through whispering tiger. Not sure if it plays the audio through the TALQu application instead though. You can have a look at the `play_audio_on_device` function in https://gist.github.com/Sharrnah/a1a53c2e2de3148d8b24fa6749691e98#file-soundboard_plugin-py-L106
- I don't think calling `processmanager.cleanup_subprocesses` is a good way as this might kill other subprocesses, possibly from other plugins as well. I would prefer using `processmanager.kill_process(process)` instead. You might have to keep track of multiple processes yourself though if you happen to run multiple.

Thanks again for the hard work to make a TALQu Plugin.

I would have made a PR but i didn't get TALQu running for me at the moment.

btw. I added your plugin to the official listing in Whispering Tiger. (I hope thats fine). 😄

**Comment by rokujyushi** [comment]
I am late to confirm this!
Thanks for the suggestion!
I'll go ahead and make improvements!
